apiVersion: v1
kind: ConfigMap
metadata:
  name: db-payment-api-config
  labels:
    name: db-payment-api-config
data:
  DB_NAME: payment-api-database
  DB_PORT: "5432"
  PGSSLMODE: no-verify
  ORDER_API_HOST: http://svc-order-api/api/v1